### GET Request
GET http://localhost:3000/task/

### POST Request
POST http://localhost:3000/task/create
Content-Type: application/json

{
    "id": 0,
    "name": "This is a test post",
    "dueDate": "une date",
    "priority": "low"
}
