### GET Request
GET http://localhost:3000/task/

### GET Request
GET http://localhost:3000/task/1

### POST Request
POST http://localhost:3000/task/create
Content-Type: application/json

{
    "id": 0,
    "name": "This is a test post",
    "dueDate": "une date",
    "priority": "low"
}

### PATCH Request
PATCH http://localhost:3000/task/update
Content-Type: application/json

{
    "id": 1,
    "name": "caca",
    "dueDate": "caca",
    "priority": "low"
}

### DELETE Request
DELETE http://localhost:3000/task/delete/1

